- name: Directory is present
  file:
    path: /data/registry
    state: directory
  tags: [registry]

- name: Container is running  
  docker:
    image: registry
    name: registry
    ports: 5000:5000
    privileged: yes
    volumes:
      - /data/registry:/tmp/registry
  tags: [registry]
